### ISSUE TITLE
Rearrange past speakers

### ISSUE THREAD

**Issue by ananyacleetus** [ReflectionsProjections/ReflectionsProjections.github.io#10]
Not sure if this is a valid issue, but past speakers should be listed in order of importance, not recency 

Edit: We've always advertised the conference with the most prominent speakers listed first. Plus, people won't look through the entire list, they'll just skim the first few

**Comment by PradyumnaShome** [comment]
@ananyacleetus Makes sense. What order would you suggest?

**Comment by ananyacleetus** [comment]
Steve Wozniak, Alexis Ohanian, Brian Fox, Jay Freeman for the first four

**Comment by WalisWang** [comment]
What about add one-line bio under speakers instead of years? Also, what about the orders for other speakers?

**Comment by ananyacleetus** [comment]
How about 

Steve Wozniak 
Alexis Ohanian
Brian Fox 

Jay Freeman
Peter Norvig
Danielle Feinberg

Travis Oliphant 
Anna Patterson
Robin Walker

Laura I Gomez 
Basil Alwan
Cassidy Williams 

Chris Gladwin
Stefan Zacchiroli
Roy Bhat?

**Comment by WalisWang** [comment]
fixed
