### ISSUE TITLE
iPad Pro responsiveness issue

### ISSUE THREAD

**Issue by redsn0w422** [ReflectionsProjections/ReflectionsProjections.github.io#18]
![d27fcdc2-aabc-4be9-a532-d619d5e04825](https://user-images.githubusercontent.com/3170794/37680768-ea8f41f4-2c52-11e8-93a8-a5621290cb64.png)

**Comment by PradyumnaShome** [comment]
Beyond the issue with the text spilling out of the card, note that the link is not aligned vertically, in the navigation bar.

**Comment by WalisWang** [comment]
@redsn0w422 should be fixed now, let me know if it still doesn't work well.

**Comment by redsn0w422** [comment]
@WalisWang looks good! I just noticed the speaker boxes aren't centered on that resolution either.

**Comment by WalisWang** [comment]
@redsn0w422 yeah, I noticed that, too. There are several problems with Ipad(pro) actually, like the loop-pattern background and the height of each section. We'll fix all those issues later.

**Comment by WalisWang** [comment]
@PradyumnaShome I have fixed the responsiveness problem of flip-cards. Can you fix the issue that "the speaker boxes aren't centered on that resolution"? thx!

**Comment by PradyumnaShome** [comment]
@redsn0w422 Could you be more specific about the issue involving centering of the speaker boxes?

**Comment by redsn0w422** [comment]
@PradyumnaShome 

![a38b778e-d6b2-49ba-ab6a-99055bb978e1](https://user-images.githubusercontent.com/3170794/37835895-3c2f8c20-2e7f-11e8-86a1-a14135172452.png)

**Comment by WalisWang** [comment]
@PradyumnaShome @redsn0w422 fixed
