### ISSUE TITLE
FAQ Background Gradient

### ISSUE THREAD

**Issue by vidushirai** [ReflectionsProjections/ReflectionsProjections.github.io#19]
The gradient does not look good - could we try a white background. Additionally - not sure if this is fixed but sometimes the flipping feature of the questions gets stuck.

**Comment by PradyumnaShome** [comment]
At one point, the flipping was an issue, but it's been fixed. Let's discuss color options at the next meeting. I am trying white for now.

**Comment by PradyumnaShome** [comment]
Update: Design has not approved neither white, nor green on dark blue (mimicking the overall theme) - we're still waiting on this from them.
