### ISSUE TITLE
Navigation bar links don't always scroll to the right element

### ISSUE THREAD

**Issue by PradyumnaShome** [ReflectionsProjections/ReflectionsProjections.github.io#21]
If you click on "Contacts" or "Contact Us", and then click on another link, say "Sponsors', it doesn't go all the way up, but just scrolls up by a little. In general, consecutive clicks on the navigation bar does not result in the right scrolling behavior.

**Comment by WalisWang** [comment]
Sorry, don't really understand this issue.  Could you add a screenshot to point it out?

**Comment by WalisWang** [comment]
@PradyumnaShome do you still have this issue on your laptop? BC it works well on mine and others' devices. I'm not sure about the reason for yours. Can you try to fix it?

**Comment by PradyumnaShome** [comment]
Navbar links work, but not the vertical arrow.

**Comment by WalisWang** [comment]
@PradyumnaShome Just fixed the scroll arrow.
