### ISSUE TITLE
Contact form for sponsors

### ISSUE THREAD

**Issue by PradyumnaShome** [ReflectionsProjections/ReflectionsProjections.github.io#29]
Replace email link with either a modal with a form, or a link to a separate page with a contact form.

**Comment by itsmesatwik** [comment]
I'm on it, could you slack me a list of things we want on the form

**Comment by PradyumnaShome** [comment]
@itsmesatwik I'm leaving it on here because it becomes easier to track.

Name, email and message for starters. It should blend with the website's theme.

Depending on how we're hosting the site (having a custom back-end or not), we might use a third-party service to actually deliver the message to the RP email address. @WalisWang Please confirm how we're going to handle the form action/request. If we're not writing a back-end, I recommend [Basin](https://usebasin.com).

@vidushirai Please update us if anything else is required.

**Comment by itsmesatwik** [comment]
I agree with using [Basin](https://usebasin.com/), it would make life easier for us.

**Comment by vidushirai** [comment]
@itsmesatwik @PradyumnaShome We're talking to HackIllinois' Systems folks and some other people to figure out what we want to do for the back end - we'll try to get back to you by the next meeting. Thanks for being on top of things 👍

**Comment by itsmesatwik** [comment]
@PradyumnaShome I added the contact form component, don't know how to link it to the contact button

**Comment by PradyumnaShome** [comment]
https://stackoverflow.com/questions/29471368/how-to-open-close-react-bootstrap-modal-programmatically
