### ISSUE TITLE
Add PuzzleBang, MechMania, ACM Symposium tabs to the About dropdown menu

### ISSUE THREAD

**Issue by modnikhil** [ReflectionsProjections/ReflectionsProjections.github.io#42]

**Comment by modnikhil** [comment]
Visit these 2 links for PB info:
https://docs.google.com/document/d/1zbxR5nHBqp2uhRFVGMsOTf83pMii3oHMPKRY6XWeiYM/edit
https://www-s.acm.illinois.edu/conference/2012/puzzlebang.php

**Comment by PradyumnaShome** [comment]
Where are we with this feature? @vibhav2799 @modnikhil

**Comment by PradyumnaShome** [comment]
Write-ups

1. MechMania
2. PuzzleBang
3. ACM Symposium
