### ISSUE TITLE
Move R|P text to navbar to free up space in the carousel area

### ISSUE THREAD

**Issue by PradyumnaShome** [ReflectionsProjections/ReflectionsProjections.github.io#54]

**Comment by itsmesatwik** [comment]
wat?

**Comment by PradyumnaShome** [comment]
We've already discussed what items we want in the navbar, and we're only making the entries smaller, so there should be no space for the logo.

**Comment by PradyumnaShome** [comment]
Just to make sure we're on the same page, the items are: About (the renamed FAQ), Events (dropdown with PuzzleBang, MechMania and Career Fair), Speakers, Sponsors and Blog.
@modnikhil , tagging for confirmation.
