### ISSUE TITLE
Add some more female speakers

### ISSUE THREAD

**Issue by vidushirai** [ReflectionsProjections/ReflectionsProjections.github.io#8]
A more variety of old speakers would be nice along with a link to relevant YouTube videos of their talks!

**Comment by WalisWang** [comment]
@vidushirai just Female speakers and video links have been added. But we just found videos of 2017. Are there any videos for previous years?

**Comment by PradyumnaShome** [comment]
What are we doing about this?

**Comment by aashishkapur** [comment]
Old websites can be found [here](https://acm.illinois.edu/conference)

From a quick google, it doesn't look like we have videos uploaded before 2017, but you can go though old websites and find female speakers

**Comment by aashishkapur** [comment]
Looks like there are some videos here - https://www.youtube.com/user/acmuiuc/playlists

**Comment by PradyumnaShome** [comment]
@aashishkapur Thanks for the link. @WalisWang It looks like there are videos of several years' talks, but aren't featuring anywhere close to that many speakers. I think at the meeting next week we can decide if we want to showcase some more in particular. I don't see too many women. (there are a few)
