### ISSUE TITLE
Fix "What can I do?" box

### ISSUE THREAD

**Issue by emilojkovic** [ReflectionsProjections/ReflectionsProjections.github.io#9]
Right now when I hover over the "What can I do?" box with FAQ, the box flips over with the response but won't flip back. Also, the bottom of the answer gets covered by the rotating pictures.

**Comment by emilojkovic** [comment]
Update -- so now the box is flipping back?? Not sure if that is something that still needs to be fixed?

**Comment by PradyumnaShome** [comment]
@emilojkovic All boxes flip back when no longer being hovered over.

**Comment by WalisWang** [comment]
@emilojkovic should be fixed right now, let me know if it's still not working properly

**Comment by emilojkovic** [comment]
@WalisWang 
I'm not having any more problems with the box flipping, but the bottom of "What can I do?" (the green side when it is flipped) is still getting covered by pictures. I had the same problem in Safari and Firefox (see image below).
<img width="1253" alt="box" src="https://user-images.githubusercontent.com/21327390/37677529-4c8f849a-2c49-11e8-870d-ef148c5e8cd2.png">

**Comment by PradyumnaShome** [comment]
@emilojkovic Which browser is the screen shot from? Could not reproduce in Firefox 59.0.1 (latest version)

**Comment by emilojkovic** [comment]
@PradyumnaShome I got the same problem using Safari version 11.0.3 and the latest Firefox Nightly build (61.0a1 (2018-03-20)). Firefox Nightly isn't a big concern because it's a pre-release version of Firefox. After messing around with my browsers I noticed that I can get more of the box to get covered when I shrink the window. I believe the problem boils down to how the page (and boxes) scales with window/screen size. Also for screen size reference, I am using a 13-inch MacBook Pro.

**Comment by WalisWang** [comment]
@emilojkovic just fixed it. Could you please check it again to see if there is still the problem for diff browsers?

**Comment by emilojkovic** [comment]
@WalisWang still seeing the exact same problem as before on Firefox, Safari, and Chrome

**Comment by WalisWang** [comment]
@emilojkovic Could you try to clear the cache and see if it can work properly after that? Sometimes it is because of the cache set in the browsers.

**Comment by emilojkovic** [comment]
@WalisWang Cleared all caches but it didn't change anything... I also pulled the latest version from master and ran it locally on dev and got the same results on all 3 browsers

**Comment by WalisWang** [comment]
@emilojkovic I will take a look at it later. Also, try to open it private mode. Simply clearing cache and history in a browser doesn't help sometimes. There is a need to clear cache for the specific website. For google chrome, the instruction is here https://productforums.google.com/forum/#!topic/chrome/YEE24sDJxfo.

**Comment by emilojkovic** [comment]
@WalisWang  Sounds good, I can show you the problems in person next week at the meeting also. I also tried clearing the cache for just the website and opening in private mode, but neither fixed it.

**Comment by WalisWang** [comment]
@emilojkovic Is it still a problem on ur laptop? If it's fixed, we can close the issue.

**Comment by emilojkovic** [comment]
Nope, everything looks great on my laptop!
